name: macOS test

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install swift-DEVELOPMENT-SNAPSHOT-2020-12-14-a
        run: |
          curl -sOL https://swift.org/builds/development/xcode/swift-DEVELOPMENT-SNAPSHOT-2020-12-14-a/swift-DEVELOPMENT-SNAPSHOT-2020-12-14-a-osx.pkg
          xattr -dr com.apple.quarantine swift-DEVELOPMENT-SNAPSHOT-2020-12-14-a-osx.pkg
          installer -pkg swift-DEVELOPMENT-SNAPSHOT-2020-12-14-a-osx.pkg -target CurrentUserHomeDirectory
      - name: Set Environment Variables
        run: |
          export TOOLCHAIN_NAME=$(echo $HOME/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-* | sed -e 's#.*/Library#/Library#')
          export DATE=$(date -j +%Y%m%d)
          echo "TOOLCHAINS=..." > $GITHUB_ENV

      - name: Install X10
        run: |
          curl -sL https://artprodeus21.artifacts.visualstudio.com/A8fd008a0-56bc-482c-ba46-67f9425510be/3133d6ab-80a8-4996-ac4f-03df25cd3224/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2NvbXBuZXJkL3Byb2plY3RJZC8zMTMzZDZhYi04MGE4LTQ5OTYtYWM0Zi0wM2RmMjVjZDMyMjQvYnVpbGRJZC80NTU3NC9hcnRpZmFjdE5hbWUvdGVuc29yZmxvdy1kYXJ3aW4teDY00/content?format=zip -o tensorflow-darwin-x64.zip
          unzip tensorflow-darwin-x64.zip
          mv tensorflow-darwin-x64/Library/tensorflow-2.4.0 ~/Library/

      - name: Build tensorflow/swift-apis
        run: |
          TOOLCHAINS=org.swift.50202012141a swift build -v -Xswiftc -DTENSORFLOW_USE_STANDARD_TOOLCHAIN -Xcc -I${HOME}/Library/tensorflow-2.4.0/usr/include -Xlinker -L${HOME}/Library/tensorflow-2.4.0/usr/lib

    # - name: Run tests
    #   run: |
    #     DYLD_LIBRARY_PATH=${HOME}/Library/tensorflow-2.4.0/usr/lib TOOLCHAINS=org.swift.50202012141a swift test -v -Xswiftc -DTENSORFLOW_USE_STANDARD_TOOLCHAIN -Xcc -I${HOME}/Library/tensorflow-2.4.0/usr/include -Xlinker -L${HOME}/Library/tensorflow-2.4.0/usr/lib

      - name: Build toolchain package
        run: |
          pkgbuild --identifier org.tensorflow-${DATE}              \
                   --install-location /Library/Developer/Toolchains/${TOOLCHAIN_NAME}.xctoolchain  \
                   --version 5.0.${DATE} \ 
                   --root ${TOOLCHAIN_NAME}
                   ${TOOLCHAIN_NAME}.pkg

# pkgbuild --root "${TOOLCHAIN_PREFIX}" --install-location "${DARWIN_TOOLCHAIN_INSTALL_LOCATION}" "${DARWIN_INSTALLER_PACKAGE}" \
#          --version "${DARWIN_TOOLCHAIN_VERSION}" --identifier "${DARWIN_BUNDLE_IDENTIFIER}" --sign "${DARWIN_INSTALLER_CERT}" \
#          --scripts "${DARWIN_SCRIPTS}"
# 
# TOOLCHAIN_PREFIX=/Users/danielzheng/swift-dev/swift-nightly-install//Library/Developer/Toolchains/swift-LOCAL-2021-01-04-a.xctoolchain/
# DARWIN_BUNDLE_IDENTIFIER=local.20210104
# DARWIN_INSTALLER_CERT=cert
# DARWIN_INSTALLER_PACKAGE=pkg
# DARWIN_TOOLCHAIN_INSTALL_LOCATION=/Library/Developer/Toolchains/swift-LOCAL-2021-01-04-a.xctoolchain
# DARWIN_TOOLCHAIN_VERSION=5.0.20210104
# /DARWIN_SCRIPTS=Users/danielzheng/swift-dev/swift/utils/darwin-installer-scripts

          # pkgbuild --identifier org.compnerd.dt.toolchain.${{ parameters.alias }}-$(date -j +%Y%m%d)              \
          #          --install-location /Library/Developer/Toolchains/unknown-Asserts-$(Build.BuildId).xctoolchain  \
          #          --scripts $(Build.BinariesDirectory)/pkgscripts                                                \
          #          --version $(Build.BuildId)                                                                     \
          #          --root $(toolchain.directory)                                                                  \
          #          $(Build.ArtifactStagingDirectory)/toolchain-darwin-${{ parameters.host }}.pkg
